### ISSUE TITLE
Feature_Request-Autofill metadata from ISBN code

### ISSUE THREAD

**Issue by ghost** [Geremia/LibgenBulkUpload#1]
I humbly request the metadata auto-completion function from the book's ISBN.
In the upload channel "https://library.bz/main/upload/" of the same libgen portal, after uploading an ebook, it is possible to auto-fill the book's metadata from its ISBN through some search engines, such as amazon or goodreaders, googlebooks and others...

Thus, it would be very useful for the project to gain the function that, if the ISBN is entered in the file name, the metadata search is performed and the ebook comes up not only with author and title data, but several others. (year, language, edition, cover, publisher...)

Ex:
Title - Author - ISBN.ext
Sapiens A Brief History of Humankind - Yuval Noah Harari - 0062316095.pdf

**Comment by Geremia** [comment]
@apenasrr Doesn't Libgen already extract metadata from uploaded files?
