### ISSUE TITLE
Would a Libgen.rs version be possible?

### ISSUE THREAD

**Issue by Tenome** [Geremia/LibgenBulkUpload#3]
This is a useful script, but I'd prefer to upload to .rs since anything uploaded there will be mirrored on .lc anyway (but .rs doesn't mirror .lc). Would it be possible to write a script for https://library.bz/fiction/upload/ ?

Thank you.

**Comment by Geremia** [comment]
@Tenome What's the username and password for https://library.bz/fiction/upload/ ?
You should be able to edit [upload.py](https://github.com/Geremia/LibgenBulkUpload/blob/main/upload.py) with the correct URLs.

**Comment by Tenome** [comment]
It's genesis:upload, but it needs a bit of tweaking because the login is a pop-up instead. 
https://puu.sh/Jozxr/37d1b1fabe.png

Simply replacing the URL will give a 401 Authorization Required error (cmd says that the popup was dismissed).

**Comment by Geremia** [comment]
@Tenome Selenium can probably handle that.

**Comment by Tenome** [comment]
I'd have no idea how to do it though. Would you be able to write something to handle the popup?

**Comment by Geremia** [comment]
@Tenome Perhaps I'll make a new branch to handle https://library.bz/main/upload/ .
https://libgen.lc/community/ucp.php?mode=login doesn't allow logins anymore ("You exceeded the maximum allowed number of login attempts."), so I can't get a session ID to upload there.
Library.bz doesn't appear to require cookies / session ID.

**Comment by Geremia** [comment]
@Tenome  See the [`library.bz` branch](https://github.com/Geremia/LibgenBulkUpload/tree/library.bz)'s [`upload.bash`](https://github.com/Geremia/LibgenBulkUpload/blob/library.bz/upload.bash).
